### ISSUE TITLE
Using __esri namespace in more than one component

### ISSUE THREAD

**Issue by mfcallahan** [Esri/angular-cli-esri-map#30]
I've noticed that I am unable to use the `__esri` namespace in more than one component or service in my applicaiton.  For example, I have a `MapComponent` class which sets up my basemap, and and a `LegendComponent` class which sets up an interactive legend to turn on/off layers.  However, when I attempt to use access the `__esri` namespace in the `LegendComponent` class, I get this error:
```
ReferenceError: __esri is not defined
    at Module../src/app/legend/legend.component.ts (c:\...\src\app\legend\legend.component.ts:3:15)
    at __webpack_require__ (http://localhost:4200/runtime.js:79:30)
    at Module../src/app/app.module.ts (http://localhost:4200/main.js:137:105)
    at __webpack_require__ (http://localhost:4200/runtime.js:79:30)
    at Module../src/main.ts (c:\...\src\main.ts:1:1)
    at __webpack_require__ (http://localhost:4200/runtime.js:79:30)
    at Object.0 (http://localhost:4200/main.js:1009:18)
    at __webpack_require__ (http://localhost:4200/runtime.js:79:30)
    at checkDeferredModules (http://localhost:4200/runtime.js:46:23)
    at Array.webpackJsonpCallback [as push] (http://localhost:4200/runtime.js:33:19)
```
Removing the `LegendComponent` class from the application resolves the error.  How can I use the `__esri` namespace in places other than just a single component?

**Comment by andygup** [comment]
@mfcallahan can you provide a stackblitz that reproduces the issue? I've seen some weird stuff recently with Angular material and namespaces. Any chance you are using Angular material?

Here's a working non-material example: https://stackblitz.com/edit/angular-cli-esri-map2-test?file=src%2Fapp%2Fmap-text%2Fmap-text.component.ts

**Comment by Adondriel** [comment]
I had to add 
`    "types": ["arcgis-js-api"]
`
to my tsconfig, even though I'm using v7.2 of angular.

**Comment by andygup** [comment]
Oh, that's interesting, thanks for the update. We tested quite a bit with v7.2 but with so many interdependencies these days it's hard to capture all permutations. I'll close this for now.

**Comment by mfcallahan** [comment]
Hi thanks for the follow up - I will post an example tomorrow.
